import { Metadata } from "next";
import getUsers from "../actions/getUsers";
import Sidebar from "../components/sidebar/Sidebar";
import UserList from "./components/UserList";

export const metadata: Metadata = {
    title: 'User List',
    description: 'Generated by create next app',
    icons: {
        icon: "/images/favicon.png",
      }
  }

export default async function UsersLayout({
    children
}: {
    children: React.ReactNode;
}) {
    const users = await getUsers();
    return (
        <Sidebar>
            <div className="h-full">
                <UserList items={users} />
                {children}
            </div>
        </Sidebar>
    )
};